### ISSUE TITLE
Cannot use itemcrack type of drawDot effect

### ISSUE THREAD

**Issue by rudde0** [811Alex/skDragon#2]
```
drawDot count 8, particle "itemcrack", material diamond, XYZ 0.3, 0.9, 0.3, center player, rainbowMode false, visibleRange 32, pulseDelay 1, keepFor 20 ticks
```
when I'm trying to execute the code above I'm getting this error:
```
[16:56:25 WARN]: [skDragon] Task #124263 for skDragon v0.17 generated an exception
ud.skript.sashie.skDragon.particleEngine.utils.ParticleEffect$ParticlePacket$PacketInstantiationException: Packet instantiation failed
        at ud.skript.sashie.skDragon.particleEngine.utils.ParticleEffect$ParticlePacket.initializePacket(ParticleEffect.java:1138) ~[skDragon-0.17-alex-MC1.18-hack.jar:?]
        at ud.skript.sashie.skDragon.particleEngine.utils.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:1144) ~[skDragon-0.17-alex-MC1.18-hack.jar:?]
        at ud.skript.sashie.skDragon.particleEngine.utils.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:1178) ~[skDragon-0.17-alex-MC1.18-hack.jar:?]
        at ud.skript.sashie.skDragon.particleEngine.utils.ParticleEffect.display(ParticleEffect.java:321) ~[skDragon-0.17-alex-MC1.18-hack.jar:?]
        at ud.skript.sashie.skDragon.particleEngine.utils.ParticleEffect.display(ParticleEffect.java:415) ~[skDragon-0.17-alex-MC1.18-hack.jar:?]
        at ud.skript.sashie.skDragon.particleEngine.effects.EffDot$1.run(EffDot.java:122) ~[skDragon-0.17-alex-MC1.18-hack.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1434]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1434]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1571) ~[purpur-1.18.1.jar:git-Purpur-1434]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.1.jar:git-Purpur-1434]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.1.jar:git-Purpur-1434]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1434]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1434]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at ud.skript.sashie.skDragon.particleEngine.utils.ParticleEffect$ParticlePacket.initializePacket(ParticleEffect.java:1096) ~[skDragon-0.17-alex-MC1.18-hack.jar:?]
        ... 13 more
Caused by: java.lang.ClassCastException
```
there are no issue except "itemcrack" type in drawdot, my guess is there should an error about casting the itemstack

**Comment by 811Alex** [comment]
Thanks for giving the skript code that causes it too.

Seems to be caused by the "barrier" particle not existing on 1.18, which makes half the particles in the game having a different ID. The one after "itemcrack" makes it throw an exception too, so that's nice, helps notice the issue. I'll add a patch, it should fix this barfing errors and potentially other usable particles being scrambled.
